# 控制哪些榜单启用 (true/false)
enabled-boards:
  mining: true
  placing: true
  pvp: true
  mob: true
  daoguan: true
  void: true
  suicide: true
  discard: true

# 各榜单权限奖励设置
board-rewards:
  mining:
    permission: "cfc.watuji"
    required-points: 100000
  placing:
    permission: "cfc.fangzhi"
    required-points: 10000
  pvp:
    permission: "cfc.bidong"
    required-points: 100
  mob:
    permission: "cfc.lieren"
    required-points: 2000
  void:
    permission: "cfc.xukong"
    required-points: 50000
  suicide:
    permission: "cfc.ziwozhuzai"
    required-points: 3000
  discard:
    permission: "cfc.diuqi"
    required-points: 100000
  daoguan:
    permission: "cfc.daoguan"
    required-points: 1000
    wei-ai-mu-id: "WeiAiMu"
    points-per-second-near-wei-ai-mu: 10
    points-per-3-seconds: 1
  
  #关于排行榜上ID颜色
  #color.admin 红色（管理）
  #color.liteadmin 金色（协管）
  #color.mod 绿色（客服）
  #color.pro 蓝色（类似于高级玩家）
  #---
  #本插件初次授权于 ColorFulCraft Network，可能存在水印
  #使用/wjb 显示/隐藏 榜单
  #使用/wjb reload 重载
  #使用/wjb info 查看相关信息
  #---
  #本插件采取ID记录的方法，防止某些特定操作导致uuid变动而数据变动